name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }} with .NET ${{ matrix.dotnet }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
        dotnet: [ '6.0.x', '7.0.x' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Clean package cache
        working-directory: ./
        run: dotnet clean -c Release && dotnet nuget locals all --clear
      - name: Build
        working-directory: ./
        run: dotnet build -c Release

  test:
    name: Tests on ${{ matrix.os }} with .NET ${{ matrix.dotnet }}
    needs: [build]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        dotnet: [ '6.0.x', '7.0.x' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Clean package cache
        working-directory: ./
        run: dotnet clean -c Release && dotnet nuget locals all --clear
      - name: Test
        working-directory: ./
        run: dotnet test --logger:trx

  update_release_draft:
    name: Release Drafter
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}