name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
         
    - name: Setup .NET Core @ Latest
      uses: actions/setup-dotnet@v1
      with:
        source-url: https://api.nuget.org/v3/index.json
        dotnet-version: '5.0'
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}

    - name: Build Project
      run: |
        dotnet build AdvancedEmailValidator --configuration Release
    - name: Build solution and generate NuGet package
      run: |  
        cd AdvancedEmailValidator
        dotnet pack -c Release -o out /p:version=${{ github.event.release.tag_name }} /p:ContinuousIntegrationBuild=true
    - name: Push generated package to NuGet registry
      run: dotnet nuget push ./AdvancedEmailValidator/out/*.nupkg -k ${{secrets.NUGET_API_KEY}} --skip-duplicate --no-symbols true
